x=-5:5;
subplot(3,4,1)
plot(x,compet(x))
title('compet'); 
subplot(3,4,2)
plot(x,hardlims(x))
title('hardlims'); 
subplot(3,4,3)
plot(x,logsig(x))
title('logsig'); 
subplot(3,4,4)
plot(x,poslin(x))
title('poslin'); 
subplot(3,4,5)
plot(x,purelin(x))
title('purelin'); 
subplot(3,4,6)
plot(x,radbas(x))
title('radbas'); 
subplot(3,4,7)
plot(x,satlin(x))
title('satlin'); 
subplot(3,4,8)
plot(x,satlins(x))
title('satlins'); 
subplot(3,4,9)
plot(x,softmax(x))
title('softmax'); 
subplot(3,4,10)
plot(x,tansig(x))
title('tansig'); 
subplot(3,4,11)
plot(x,tribas(x))
title('tribas'); 
